version: '3.4'

services:
  organicclient:
    image: organicclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7500:7500
